workflows:
  build-and-deploy:
    name: Build and Deploy
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_WORKSPACE: "MovieHub/Modularization.xcworkspace" # Isikan nama project Anda.
          XCODE_SCHEME: "MovieHub" # Isikan nama scheme project Anda.
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods
      - name: Pod Install
        script: |
          pod install --project-directory=MovieHub
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - egifcb@gmail.com
